<?
//base de datos
/*
define("host","localhost");
define("user","root");
define("pass","pass");
define("database","inovadb");
define("base","http://localhost/inova_home");
*/
/*
define("host","localhost");
define("user","root");
define("pass","inovatel210980");
define("database","inovadb");
define("base","http://66.128.53.140/inova_home");
//define("base","http://localhost/inova_home");
*/
/*
define("host","localhost");
define("user","inova");
define("pass","inova");
define("database","inovadb");
//define("base","http://localhost/inova_home/");
define("base","http://66.128.53.140/inova_home");
*/
define("host","66.128.53.140");
define("user","inova");
define("pass","inova");
define("database","inovadb");
//define("base","http://localhost/inova_home/");
define("base","http://66.128.53.140/inova_home");

?>